language: generic 
sudo: required
services:
  - docker

before-install:
  - docker build -t alvinotutu/docker-react  -f Dockerfile.dev .

script:
  - docker run -e CI=true alvinotutu/docker-react npm run test 